import { formatDate, formatNumber, getLanguage, isRtl, milestoneLabel } from '../core/i18n.js';
import { getCompany, getSalesIdentity } from '../core/settings.js';
import { getCustomer } from '../core/repos/sales.js';
import { getPiByQuote, type ProformaInvoice } from '../core/repos/billing.js';
import { documentStyles, escapeHtml, renderDocument, type RenderedDocument } from './document.js';

/**
 * Proforma invoice (形式发票).
 *
 * Deliberately built on the same renderer and layout language as the quotation —
 * a buyer should recognise it as "the same document, one step later", not as a
 * different company's paperwork. What changes is the content: PI number instead
 * of quote number, a payment schedule with due dates, and the bank details a
 * buyer needs in order to actually pay.
 */

interface PiLabels {
  title: string;
  piNo: string;
  quoteRef: string;
  date: string;
  validUntil: string;
  seller: string;
  buyer: string;
  attn: string;
  item: string;
  description: string;
  qty: string;
  unit: string;
  unitPrice: string;
  amount: string;
  subtotal: string;
  freight: string;
  insurance: string;
  total: string;
  paymentSchedule: string;
  milestone: string;
  dueDate: string;
  amountDue: string;
  status: string;
  deposit: string;
  balance: string;
  paid: string;
  pending: string;
  overdue: string;
  bankDetails: string;
  terms: string;
  incoterm: string;
  shipment: string;
  notes: string;
  signature: string;
  stamp: string;
  declaration: string;
  generated: string;
}

const LABELS: Record<string, PiLabels> = {
  en: {
    title: 'PROFORMA INVOICE', piNo: 'PI No.', quoteRef: 'Quotation', date: 'Date', validUntil: 'Valid until',
    seller: 'Beneficiary', buyer: 'Applicant', attn: 'Attn', item: '#', description: 'Description', qty: 'Qty',
    unit: 'Unit', unitPrice: 'Unit price', amount: 'Amount', subtotal: 'Subtotal', freight: 'Freight',
    insurance: 'Insurance', total: 'TOTAL', paymentSchedule: 'Payment schedule', milestone: 'Milestone',
    dueDate: 'Due date', amountDue: 'Amount', status: 'Status', deposit: 'Deposit', balance: 'Balance',
    paid: 'Paid', pending: 'Pending', overdue: 'Overdue', bankDetails: 'Bank details', terms: 'Terms',
    incoterm: 'Incoterm', shipment: 'Shipment', notes: 'Notes', signature: 'Authorised signature',
    stamp: 'Company stamp',
    declaration: 'This proforma invoice is issued for the purpose of payment and import formalities. It is not a tax invoice.',
    generated: 'Generated by DealTrack',
  },
  zh: {
    title: '形 式 发 票', piNo: 'PI 编号', quoteRef: '对应报价单', date: '日期', validUntil: '有效期至',
    seller: '收款人', buyer: '申请人', attn: '联系人', item: '序号', description: '品名 / 规格', qty: '数量',
    unit: '单位', unitPrice: '单价', amount: '金额', subtotal: '小计', freight: '运费', insurance: '保险费',
    total: '总 计', paymentSchedule: '付款计划', milestone: '款项', dueDate: '应付日期', amountDue: '金额',
    status: '状态', deposit: '定金', balance: '尾款', paid: '已付', pending: '待付', overdue: '已逾期',
    bankDetails: '银行信息', terms: '条款', incoterm: '贸易条款', shipment: '预计出运', notes: '备注',
    signature: '授权签字', stamp: '公司盖章',
    declaration: '本形式发票用于付款与进口清关手续，非税务发票。',
    generated: '由 DealTrack 生成',
  },
  es: {
    title: 'FACTURA PROFORMA', piNo: 'N.º PI', quoteRef: 'Cotización', date: 'Fecha', validUntil: 'Válida hasta',
    seller: 'Beneficiario', buyer: 'Solicitante', attn: 'Attn.', item: '#', description: 'Descripción', qty: 'Cant.',
    unit: 'Unidad', unitPrice: 'Precio unit.', amount: 'Importe', subtotal: 'Subtotal', freight: 'Flete',
    insurance: 'Seguro', total: 'TOTAL', paymentSchedule: 'Calendario de pagos', milestone: 'Hito',
    dueDate: 'Vencimiento', amountDue: 'Importe', status: 'Estado', deposit: 'Anticipo', balance: 'Saldo',
    paid: 'Pagado', pending: 'Pendiente', overdue: 'Vencido', bankDetails: 'Datos bancarios', terms: 'Condiciones',
    incoterm: 'Incoterm', shipment: 'Embarque', notes: 'Notas', signature: 'Firma autorizada',
    stamp: 'Sello de la empresa',
    declaration: 'Esta factura proforma se emite a efectos de pago y trámites de importación. No es una factura fiscal.',
    generated: 'Generado por DealTrack',
  },
  fr: {
    title: 'FACTURE PROFORMA', piNo: 'N° PI', quoteRef: 'Devis', date: 'Date', validUntil: 'Valable jusqu’au',
    seller: 'Bénéficiaire', buyer: 'Demandeur', attn: 'À l’attention de', item: '#', description: 'Désignation',
    qty: 'Qté', unit: 'Unité', unitPrice: 'Prix unitaire', amount: 'Montant', subtotal: 'Sous-total',
    freight: 'Fret', insurance: 'Assurance', total: 'TOTAL', paymentSchedule: 'Échéancier de paiement',
    milestone: 'Échéance', dueDate: 'Date d’échéance', amountDue: 'Montant', status: 'Statut',
    deposit: 'Acompte', balance: 'Solde', paid: 'Payé', pending: 'En attente', overdue: 'En retard',
    bankDetails: 'Coordonnées bancaires', terms: 'Conditions', incoterm: 'Incoterm', shipment: 'Expédition',
    notes: 'Remarques', signature: 'Signature autorisée', stamp: 'Cachet de l’entreprise',
    declaration: 'Cette facture proforma est émise pour le paiement et les formalités d’importation. Ce n’est pas une facture fiscale.',
    generated: 'Généré par DealTrack',
  },
  de: {
    title: 'PROFORMARECHNUNG', piNo: 'PI-Nr.', quoteRef: 'Angebot', date: 'Datum', validUntil: 'Gültig bis',
    seller: 'Begünstigter', buyer: 'Antragsteller', attn: 'z. Hd.', item: '#', description: 'Bezeichnung',
    qty: 'Menge', unit: 'Einheit', unitPrice: 'Einzelpreis', amount: 'Betrag', subtotal: 'Zwischensumme',
    freight: 'Fracht', insurance: 'Versicherung', total: 'GESAMT', paymentSchedule: 'Zahlungsplan',
    milestone: 'Meilenstein', dueDate: 'Fällig am', amountDue: 'Betrag', status: 'Status',
    deposit: 'Anzahlung', balance: 'Restbetrag', paid: 'Bezahlt', pending: 'Offen', overdue: 'Überfällig',
    bankDetails: 'Bankverbindung', terms: 'Bedingungen', incoterm: 'Incoterm', shipment: 'Versand',
    notes: 'Hinweise', signature: 'Unterschrift', stamp: 'Firmenstempel',
    declaration: 'Diese Proformarechnung dient Zahlungs- und Einfuhrformalitäten. Sie ist keine Steuerrechnung.',
    generated: 'Erstellt mit DealTrack',
  },
  ru: {
    title: 'ПРОФОРМА-СЧЁТ', piNo: '№ PI', quoteRef: 'Предложение', date: 'Дата', validUntil: 'Действителен до',
    seller: 'Получатель', buyer: 'Заявитель', attn: 'Вниманию', item: '#', description: 'Наименование',
    qty: 'Кол-во', unit: 'Ед.', unitPrice: 'Цена за ед.', amount: 'Сумма', subtotal: 'Подытог',
    freight: 'Фрахт', insurance: 'Страхование', total: 'ИТОГО', paymentSchedule: 'График платежей',
    milestone: 'Этап', dueDate: 'Срок оплаты', amountDue: 'Сумма', status: 'Статус',
    deposit: 'Аванс', balance: 'Остаток', paid: 'Оплачено', pending: 'Ожидает', overdue: 'Просрочено',
    bankDetails: 'Банковские реквизиты', terms: 'Условия', incoterm: 'Инкотермс', shipment: 'Отгрузка',
    notes: 'Примечания', signature: 'Подпись', stamp: 'Печать компании',
    declaration: 'Настоящий проформа-счёт выставлен для оплаты и таможенного оформления. Не является налоговым счётом.',
    generated: 'Сформировано в DealTrack',
  },
  ar: {
    title: 'فاتورة مبدئية', piNo: 'رقم الفاتورة', quoteRef: 'عرض السعر', date: 'التاريخ', validUntil: 'صالحة حتى',
    seller: 'المستفيد', buyer: 'مقدم الطلب', attn: 'عناية', item: '#', description: 'الوصف', qty: 'الكمية',
    unit: 'الوحدة', unitPrice: 'سعر الوحدة', amount: 'المبلغ', subtotal: 'المجموع الفرعي', freight: 'الشحن',
    insurance: 'التأمين', total: 'الإجمالي', paymentSchedule: 'جدول الدفعات', milestone: 'الدفعة',
    dueDate: 'تاريخ الاستحقاق', amountDue: 'المبلغ', status: 'الحالة', deposit: 'الدفعة المقدمة',
    balance: 'الرصيد', paid: 'مدفوع', pending: 'قيد الانتظار', overdue: 'متأخر', bankDetails: 'البيانات البنكية',
    terms: 'الشروط', incoterm: 'شرط التسليم', shipment: 'الشحن', notes: 'ملاحظات', signature: 'التوقيع المعتمد',
    stamp: 'ختم الشركة',
    declaration: 'هذه الفاتورة المبدئية صادرة لأغراض الدفع وإجراءات الاستيراد، وليست فاتورة ضريبية.',
    generated: 'تم الإنشاء بواسطة DealTrack',
  },
  pt: {
    title: 'FATURA PROFORMA', piNo: 'N.º PI', quoteRef: 'Cotação', date: 'Data', validUntil: 'Válida até',
    seller: 'Beneficiário', buyer: 'Solicitante', attn: 'A/C', item: '#', description: 'Descrição', qty: 'Qtd.',
    unit: 'Un.', unitPrice: 'Preço unit.', amount: 'Valor', subtotal: 'Subtotal', freight: 'Frete',
    insurance: 'Seguro', total: 'TOTAL', paymentSchedule: 'Cronograma de pagamento', milestone: 'Etapa',
    dueDate: 'Vencimento', amountDue: 'Valor', status: 'Status', deposit: 'Entrada', balance: 'Saldo',
    paid: 'Pago', pending: 'Pendente', overdue: 'Vencido', bankDetails: 'Dados bancários',
    terms: 'Condições', incoterm: 'Incoterm', shipment: 'Embarque', notes: 'Observações',
    signature: 'Assinatura autorizada', stamp: 'Carimbo da empresa',
    declaration: 'Esta fatura proforma é emitida para fins de pagamento e desembaraço de importação. Não é uma fatura fiscal.',
    generated: 'Gerado por DealTrack',
  },
  ja: {
    title: 'プ ロ フ ォ ー マ イ ン ボ イ ス', piNo: 'PI 番号', quoteRef: '見積書', date: '日付', validUntil: '有効期限',
    seller: '受益者', buyer: '申請者', attn: 'ご担当', item: '#', description: '品名・仕様', qty: '数量',
    unit: '単位', unitPrice: '単価', amount: '金額', subtotal: '小計', freight: '運賃', insurance: '保険',
    total: '合 計', paymentSchedule: '支払スケジュール', milestone: '支払区分', dueDate: '支払期日',
    amountDue: '金額', status: '状況', deposit: '前払金', balance: '残金', paid: '支払済',
    pending: '未払', overdue: '延滞', bankDetails: '銀行口座', terms: '条件', incoterm: 'インコタームズ',
    shipment: '出荷予定', notes: '備考', signature: '署名', stamp: '社印',
    declaration: '本書は支払および輸入通関手続きのためのプロフォーマインボイスであり、税務上の請求書ではありません。',
    generated: 'DealTrack により作成',
  },
  ko: {
    title: '견 적 송 장', piNo: 'PI 번호', quoteRef: '견적서', date: '날짜', validUntil: '유효기간',
    seller: '수취인', buyer: '신청인', attn: '담당자', item: '#', description: '품명 / 규격', qty: '수량',
    unit: '단위', unitPrice: '단가', amount: '금액', subtotal: '소계', freight: '운임', insurance: '보험',
    total: '합 계', paymentSchedule: '결제 일정', milestone: '결제 단계', dueDate: '납부 기한',
    amountDue: '금액', status: '상태', deposit: '계약금', balance: '잔금', paid: '완납',
    pending: '미납', overdue: '연체', bankDetails: '은행 정보', terms: '조건', incoterm: '인코텀즈',
    shipment: '선적 예정', notes: '비고', signature: '서명', stamp: '회사 직인',
    declaration: '본 견적송장은 결제 및 수입 통관용이며 세금계산서가 아닙니다.',
    generated: 'DealTrack 생성',
  },
};

export function piLabels(language: string): PiLabels {
  return LABELS[language.split('-')[0]!] ?? LABELS.en!;
}

const MILESTONE_STATUS: Record<string, Record<string, string>> = {
  paid: { en: 'Paid', zh: '已付', es: 'Pagado', fr: 'Payé', de: 'Bezahlt', ru: 'Оплачено', ar: 'مدفوع', pt: 'Pago', ja: '支払済', ko: '완납' },
  pending: { en: 'Pending', zh: '待付', es: 'Pendiente', fr: 'En attente', de: 'Offen', ru: 'Ожидает', ar: 'قيد الانتظار', pt: 'Pendente', ja: '未払', ko: '미납' },
  invoiced: { en: 'Invoiced', zh: '已开票', es: 'Facturado', fr: 'Facturé', de: 'Berechnet', ru: 'Выставлен', ar: 'مفوتر', pt: 'Faturado', ja: '請求済', ko: '청구됨' },
  overdue: { en: 'Overdue', zh: '已逾期', es: 'Vencido', fr: 'En retard', de: 'Überfällig', ru: 'Просрочено', ar: 'متأخر', pt: 'Vencido', ja: '延滞', ko: '연체' },
  waived: { en: 'Waived', zh: '已减免', es: 'Renunciado', fr: 'Annulé', de: 'Erlassen', ru: 'Отменён', ar: 'معفى', pt: 'Isento', ja: '免除', ko: '면제' },
};

function localized(table: Record<string, Record<string, string>>, key: string, language: string, fallback: string): string {
  const entry = table[key];
  if (!entry) return fallback;
  return entry[language.split('-')[0]!] ?? entry.en ?? fallback;
}

export function buildPiHtml(quoteId: string): { html: string; baseName: string; language: string } | null {
  const pi = getPiByQuote(quoteId);
  if (!pi) return null;
  return buildPiHtmlFrom(pi);
}

export function buildPiHtmlFrom(pi: ProformaInvoice): { html: string; baseName: string; language: string } | null {
  const quote = pi.quote;
  if (!quote) return null;

  const customer = getCustomer(pi.customerId);
  const company = getCompany();
  const sales = getSalesIdentity();
  const language = pi.language || 'en';
  const labels = piLabels(language);
  const rtl = isRtl(language);
  const money = (value: number) => formatNumber(value, language, 2);
  const date = (value: string | null | undefined) => (value ? formatDate(value, language) : '—');

  const rows = (quote.items ?? [])
    .map(
      (item) => `
      <tr>
        <td class="num">${item.lineNo}</td>
        <td>
          <div>${escapeHtml(item.description)}</div>
          ${item.sku ? `<div class="sku">SKU ${escapeHtml(item.sku)}${item.hsCode ? ` · HS ${escapeHtml(item.hsCode)}` : ''}</div>` : ''}
        </td>
        <td class="num">${formatNumber(item.qty, language, 0)}</td>
        <td>${escapeHtml(item.unit)}</td>
        <td class="num">${money(item.unitPrice)}</td>
        <td class="num">${money(item.amount)}</td>
      </tr>`,
    )
    .join('');

  const milestones = (pi.milestones ?? [])
    .map(
      (milestone) => `
      <tr>
        <td>${escapeHtml(milestoneLabel(milestone.label, language))}</td>
        <td>${date(milestone.dueAt)}</td>
        <td class="num">${escapeHtml(milestone.currency)} ${money(milestone.amount)}</td>
        <td><span class="badge ${milestone.status === 'paid' ? 'ok' : milestone.status === 'overdue' ? 'bad' : 'warn'}">${escapeHtml(
          localized(MILESTONE_STATUS, milestone.status, language, milestone.status),
        )}</span></td>
      </tr>`,
    )
    .join('');

  const html = `<!doctype html>
<html lang="${escapeHtml(language)}" dir="${rtl ? 'rtl' : 'ltr'}">
<head>
<meta charset="utf-8" />
<title>${escapeHtml(pi.piNo)} · ${escapeHtml(customer?.company ?? '')}</title>
<style>${documentStyles('#1c6b4a')}</style>
</head>
<body class="${rtl ? 'rtl' : ''}">
<div class="doc">
  <header class="doc-header">
    <div>
      <div class="seller-name">${escapeHtml(company.name)}</div>
      ${company.nameZh ? `<div class="seller-meta">${escapeHtml(company.nameZh)}</div>` : ''}
      <div class="seller-meta">${escapeHtml([company.address, `${company.city}, ${company.country}`].filter(Boolean).join('\n'))}</div>
      <div class="seller-meta"><bdi>${escapeHtml([company.email, company.phone].filter(Boolean).join(' · '))}</bdi></div>
    </div>
    <div class="doc-title">
      <div class="label">${labels.title}</div>
      <div class="no">${escapeHtml(pi.piNo)}</div>
      <div class="date">${labels.date}: ${date(pi.issuedAt)}</div>
      <div class="date">${labels.quoteRef}: ${escapeHtml(quote.quoteNo)}</div>
      <div class="date">${labels.validUntil}: ${date(pi.validUntil)}</div>
    </div>
  </header>

  <section class="parties">
    <div class="party">
      <h3>${labels.buyer}</h3>
      <div class="name">${escapeHtml(customer?.company ?? '—')}</div>
      ${customer?.contactName ? `<div class="line">${labels.attn}: ${escapeHtml(customer.contactName)}</div>` : ''}
      ${customer?.email ? `<div class="line"><bdi>${escapeHtml(customer.email)}</bdi></div>` : ''}
      ${customer?.country ? `<div class="line">${escapeHtml(customer.country)}</div>` : ''}
    </div>
    <div class="party">
      <h3>${labels.seller}</h3>
      <div class="name">${escapeHtml(company.name)}</div>
      <div class="line">${escapeHtml(company.address)}</div>
      <div class="line">${escapeHtml(`${company.city}, ${company.country}`)}</div>
    </div>
  </section>

  <table class="items">
    <thead>
      <tr>
        <th style="width:7%">${labels.item}</th>
        <th>${labels.description}</th>
        <th style="width:11%" class="num">${labels.qty}</th>
        <th style="width:9%">${labels.unit}</th>
        <th style="width:15%" class="num">${labels.unitPrice}</th>
        <th style="width:16%" class="num">${labels.amount}</th>
      </tr>
    </thead>
    <tbody>${rows || `<tr><td colspan="6">—</td></tr>`}</tbody>
  </table>

  <div class="totals">
    <table>
      <tr><td class="label">${labels.subtotal}</td><td class="value">${escapeHtml(pi.currency)} ${money(pi.subtotal)}</td></tr>
      ${pi.freight > 0 ? `<tr><td class="label">${labels.freight}</td><td class="value">${escapeHtml(pi.currency)} ${money(pi.freight)}</td></tr>` : ''}
      ${pi.insurance > 0 ? `<tr><td class="label">${labels.insurance}</td><td class="value">${escapeHtml(pi.currency)} ${money(pi.insurance)}</td></tr>` : ''}
      <tr class="grand"><td class="label">${labels.total}</td><td class="value">${escapeHtml(pi.currency)} ${money(pi.total)}</td></tr>
    </table>
  </div>

  <h3 style="margin-top:20px; font-size:11pt">${labels.paymentSchedule}</h3>
  <table class="checklist">
    <thead>
      <tr>
        <th style="width:22%">${labels.milestone}</th>
        <th style="width:22%">${labels.dueDate}</th>
        <th style="width:24%" class="num">${labels.amountDue}</th>
        <th>${labels.status}</th>
      </tr>
    </thead>
    <tbody>${milestones || `<tr><td colspan="4">—</td></tr>`}</tbody>
  </table>

  <section class="terms" style="margin-top:16px">
    <h3>${labels.bankDetails}</h3>
    <dl>
      <dd style="grid-column:1 / -1"><bdi>${escapeHtml(pi.bankInfo || company.bankInfo)}</bdi></dd>
    </dl>
  </section>

  <section class="terms">
    <h3>${labels.terms}</h3>
    <dl>
      <dt>${labels.incoterm}</dt><dd><bdi>${escapeHtml(pi.incoterm)} ${escapeHtml(pi.incotermPlace)}</bdi></dd>
      <dt>${labels.paymentSchedule}</dt><dd><bdi>${escapeHtml(pi.paymentTerms ?? quote.paymentTerms ?? '')}</bdi></dd>
      <dt>${labels.shipment}</dt><dd>${date(pi.shipmentDate)}</dd>
    </dl>
  </section>

  ${pi.notes ? `<div class="notes">${labels.notes}: <bdi>${escapeHtml(pi.notes)}</bdi></div>` : ''}

  <section class="signature">
    <div class="block">
      <div>${labels.signature}</div>
      <div style="margin-top:16px">${escapeHtml(sales.senderName)} · ${escapeHtml(sales.senderRole)}</div>
    </div>
    <div class="stamp">${labels.stamp}</div>
  </section>

  <footer class="doc-footer">
    ${escapeHtml(labels.declaration)}<br/>
    ${labels.generated} · ${escapeHtml(pi.piNo)} · ${escapeHtml(quote.quoteNo)}
  </footer>
</div>
</body>
</html>`;

  return { html, baseName: pi.piNo, language };
}

export async function generatePiPdf(quoteId: string): Promise<string | null> {
  const built = buildPiHtml(quoteId);
  if (!built) return null;
  const rendered: RenderedDocument = await renderDocument({
    html: built.html,
    baseName: built.baseName,
    subdir: 'proforma',
  });
  return rendered.pdfPath ?? rendered.htmlPath;
}

export { getLanguage };
