import { existsSync } from 'node:fs';
import { formatDate, formatNumber, getLanguage, isRtl } from '../core/i18n.js';
import { getCompany, getSalesIdentity } from '../core/settings.js';
import { getQuote } from '../core/repos/quoting.js';
import { getCustomer } from '../core/repos/sales.js';
import { documentStyles, escapeHtml, renderDocument, type RenderedDocument } from './document.js';

/**
 * The quotation document.
 *
 * A quote PDF is the artefact a buyer forwards internally, so it has to survive
 * being read by someone who never saw the email. That means: the customer's
 * language, the customer's number format, right-to-left layout when needed, and
 * every commercial term on the page.
 */

interface DocLabels {
  quotation: string;
  quoteNo: string;
  date: string;
  validUntil: string;
  seller: string;
  buyer: string;
  attn: string;
  item: string;
  description: string;
  qty: string;
  unit: string;
  unitPrice: string;
  amount: string;
  subtotal: string;
  discount: string;
  freight: string;
  insurance: string;
  other: string;
  total: string;
  terms: string;
  incoterm: string;
  payment: string;
  leadTime: string;
  moq: string;
  currency: string;
  days: string;
  notes: string;
  signature: string;
  stamp: string;
  page: string;
  generated: string;
}

const LABELS: Record<string, DocLabels> = {
  en: {
    quotation: 'QUOTATION', quoteNo: 'No.', date: 'Date', validUntil: 'Valid until', seller: 'Seller', buyer: 'Buyer',
    attn: 'Attn', item: '#', description: 'Description', qty: 'Qty', unit: 'Unit', unitPrice: 'Unit price',
    amount: 'Amount', subtotal: 'Subtotal', discount: 'Discount', freight: 'Freight', insurance: 'Insurance',
    other: 'Other charges', total: 'TOTAL', terms: 'Commercial terms', incoterm: 'Incoterm', payment: 'Payment terms',
    leadTime: 'Lead time', moq: 'MOQ', currency: 'Currency', days: 'days', notes: 'Notes', signature: 'Authorised signature',
    stamp: 'Company stamp', page: 'Page', generated: 'Generated by DealTrack',
  },
  zh: {
    quotation: '报 价 单', quoteNo: '单号', date: '日期', validUntil: '有效期至', seller: '卖方', buyer: '买方',
    attn: '联系人', item: '序号', description: '品名 / 规格', qty: '数量', unit: '单位', unitPrice: '单价',
    amount: '金额', subtotal: '小计', discount: '折扣', freight: '运费', insurance: '保险费',
    other: '其他费用', total: '总 计', terms: '商务条款', incoterm: '贸易条款', payment: '付款方式',
    leadTime: '交货期', moq: '起订量', currency: '币种', days: '天', notes: '备注', signature: '授权签字',
    stamp: '公司盖章', page: '第', generated: '由 DealTrack 生成',
  },
  es: {
    quotation: 'COTIZACIÓN', quoteNo: 'N.º', date: 'Fecha', validUntil: 'Válida hasta', seller: 'Vendedor', buyer: 'Comprador',
    attn: 'Attn.', item: '#', description: 'Descripción', qty: 'Cant.', unit: 'Unidad', unitPrice: 'Precio unit.',
    amount: 'Importe', subtotal: 'Subtotal', discount: 'Descuento', freight: 'Flete', insurance: 'Seguro',
    other: 'Otros cargos', total: 'TOTAL', terms: 'Condiciones comerciales', incoterm: 'Incoterm', payment: 'Condiciones de pago',
    leadTime: 'Plazo de entrega', moq: 'Cantidad mínima', currency: 'Moneda', days: 'días', notes: 'Notas',
    signature: 'Firma autorizada', stamp: 'Sello de la empresa', page: 'Página', generated: 'Generado por DealTrack',
  },
  fr: {
    quotation: 'DEVIS', quoteNo: 'N°', date: 'Date', validUntil: 'Valable jusqu’au', seller: 'Vendeur', buyer: 'Acheteur',
    attn: 'À l’attention de', item: '#', description: 'Désignation', qty: 'Qté', unit: 'Unité', unitPrice: 'Prix unitaire',
    amount: 'Montant', subtotal: 'Sous-total', discount: 'Remise', freight: 'Fret', insurance: 'Assurance',
    other: 'Autres frais', total: 'TOTAL', terms: 'Conditions commerciales', incoterm: 'Incoterm', payment: 'Conditions de paiement',
    leadTime: 'Délai de livraison', moq: 'Quantité min.', currency: 'Devise', days: 'jours', notes: 'Remarques',
    signature: 'Signature autorisée', stamp: 'Cachet de l’entreprise', page: 'Page', generated: 'Généré par DealTrack',
  },
  de: {
    quotation: 'ANGEBOT', quoteNo: 'Nr.', date: 'Datum', validUntil: 'Gültig bis', seller: 'Verkäufer', buyer: 'Käufer',
    attn: 'z. Hd.', item: '#', description: 'Bezeichnung', qty: 'Menge', unit: 'Einheit', unitPrice: 'Einzelpreis',
    amount: 'Betrag', subtotal: 'Zwischensumme', discount: 'Rabatt', freight: 'Fracht', insurance: 'Versicherung',
    other: 'Sonstige Kosten', total: 'GESAMT', terms: 'Handelsbedingungen', incoterm: 'Incoterm', payment: 'Zahlungsbedingungen',
    leadTime: 'Lieferzeit', moq: 'Mindestmenge', currency: 'Währung', days: 'Tage', notes: 'Hinweise',
    signature: 'Unterschrift', stamp: 'Firmenstempel', page: 'Seite', generated: 'Erstellt mit DealTrack',
  },
  ru: {
    quotation: 'КОММЕРЧЕСКОЕ ПРЕДЛОЖЕНИЕ', quoteNo: '№', date: 'Дата', validUntil: 'Действительно до', seller: 'Продавец', buyer: 'Покупатель',
    attn: 'Вниманию', item: '#', description: 'Наименование', qty: 'Кол-во', unit: 'Ед.', unitPrice: 'Цена за ед.',
    amount: 'Сумма', subtotal: 'Подытог', discount: 'Скидка', freight: 'Фрахт', insurance: 'Страхование',
    other: 'Прочие расходы', total: 'ИТОГО', terms: 'Коммерческие условия', incoterm: 'Инкотермс', payment: 'Условия оплаты',
    leadTime: 'Срок поставки', moq: 'Мин. партия', currency: 'Валюта', days: 'дней', notes: 'Примечания',
    signature: 'Подпись', stamp: 'Печать компании', page: 'Стр.', generated: 'Сформировано в DealTrack',
  },
  ar: {
    quotation: 'عرض سعر', quoteNo: 'رقم', date: 'التاريخ', validUntil: 'صالح حتى', seller: 'البائع', buyer: 'المشتري',
    attn: 'عناية', item: '#', description: 'الوصف', qty: 'الكمية', unit: 'الوحدة', unitPrice: 'سعر الوحدة',
    amount: 'المبلغ', subtotal: 'المجموع الفرعي', discount: 'الخصم', freight: 'الشحن', insurance: 'التأمين',
    other: 'رسوم أخرى', total: 'الإجمالي', terms: 'الشروط التجارية', incoterm: 'شروط التسليم', payment: 'شروط الدفع',
    leadTime: 'مدة التسليم', moq: 'الحد الأدنى', currency: 'العملة', days: 'يوم', notes: 'ملاحظات',
    signature: 'التوقيع المعتمد', stamp: 'ختم الشركة', page: 'صفحة', generated: 'تم الإنشاء بواسطة DealTrack',
  },
  pt: {
    quotation: 'COTAÇÃO', quoteNo: 'N.º', date: 'Data', validUntil: 'Válida até', seller: 'Vendedor', buyer: 'Comprador',
    attn: 'A/C', item: '#', description: 'Descrição', qty: 'Qtd.', unit: 'Un.', unitPrice: 'Preço unit.',
    amount: 'Valor', subtotal: 'Subtotal', discount: 'Desconto', freight: 'Frete', insurance: 'Seguro',
    other: 'Outros encargos', total: 'TOTAL', terms: 'Condições comerciais', incoterm: 'Incoterm', payment: 'Condições de pagamento',
    leadTime: 'Prazo de entrega', moq: 'Pedido mínimo', currency: 'Moeda', days: 'dias', notes: 'Observações',
    signature: 'Assinatura autorizada', stamp: 'Carimbo da empresa', page: 'Página', generated: 'Gerado por DealTrack',
  },
  ja: {
    quotation: 'お 見 積 書', quoteNo: '番号', date: '日付', validUntil: '有効期限', seller: '売主', buyer: '買主',
    attn: 'ご担当', item: '#', description: '品名・仕様', qty: '数量', unit: '単位', unitPrice: '単価',
    amount: '金額', subtotal: '小計', discount: '値引', freight: '運賃', insurance: '保険',
    other: 'その他費用', total: '合 計', terms: '取引条件', incoterm: 'インコタームズ', payment: '支払条件',
    leadTime: '納期', moq: '最小注文数', currency: '通貨', days: '日', notes: '備考',
    signature: '署名', stamp: '社印', page: 'ページ', generated: 'DealTrack により作成',
  },
  ko: {
    quotation: '견 적 서', quoteNo: '번호', date: '날짜', validUntil: '유효기간', seller: '판매자', buyer: '구매자',
    attn: '담당자', item: '#', description: '품명 / 규격', qty: '수량', unit: '단위', unitPrice: '단가',
    amount: '금액', subtotal: '소계', discount: '할인', freight: '운임', insurance: '보험',
    other: '기타 비용', total: '합 계', terms: '거래 조건', incoterm: '인코텀즈', payment: '결제 조건',
    leadTime: '납기', moq: '최소 주문량', currency: '통화', days: '일', notes: '비고',
    signature: '서명', stamp: '회사 직인', page: '페이지', generated: 'DealTrack 생성',
  },
};

export function docLabels(language: string): DocLabels {
  return LABELS[language.split('-')[0]!] ?? LABELS.en!;
}

export function buildQuoteHtml(quoteId: string): { html: string; baseName: string; language: string } | null {
  const quote = getQuote(quoteId);
  if (!quote) return null;

  const customer = getCustomer(quote.customerId);
  const company = getCompany();
  const sales = getSalesIdentity();
  const language = quote.language || customer?.language || 'en';
  const labels = docLabels(language);
  const rtl = isRtl(language);
  const direction = rtl ? 'rtl' : 'ltr';
  const currency = quote.currency;

  const money = (value: number) => formatNumber(value, language, 2);
  const date = (value: string | null | undefined) => (value ? formatDate(value, language) : '—');

  const rows = (quote.items ?? [])
    .map(
      (item) => `
      <tr>
        <td class="num">${item.lineNo}</td>
        <td>
          <div>${escapeHtml(item.description)}</div>
          ${item.sku ? `<div class="sku">SKU ${escapeHtml(item.sku)}${item.hsCode ? ` · HS ${escapeHtml(item.hsCode)}` : ''}</div>` : ''}
          ${item.notes ? `<div class="sku"><bdi>${escapeHtml(item.notes)}</bdi></div>` : ''}
        </td>
        <td class="num">${formatNumber(item.qty, language, 0)}</td>
        <td>${escapeHtml(item.unit)}</td>
        <td class="num">${money(item.unitPrice)}</td>
        <td class="num">${money(item.amount)}</td>
      </tr>`,
    )
    .join('');

  const totalRows: string[] = [];
  totalRows.push(`<tr><td class="label">${labels.subtotal}</td><td class="value">${currency} ${money(quote.subtotal)}</td></tr>`);
  if (quote.discountAmount > 0) {
    totalRows.push(
      `<tr><td class="label">${labels.discount}${quote.discountPct > 0 ? ` (${formatNumber(quote.discountPct * 100, language, 1)}%)` : ''}</td><td class="value">− ${currency} ${money(quote.discountAmount)}</td></tr>`,
    );
  }
  if (quote.freight > 0) {
    totalRows.push(`<tr><td class="label">${labels.freight}</td><td class="value">${currency} ${money(quote.freight)}</td></tr>`);
  }
  if (quote.insurance > 0) {
    totalRows.push(`<tr><td class="label">${labels.insurance}</td><td class="value">${currency} ${money(quote.insurance)}</td></tr>`);
  }
  if (quote.otherFees > 0) {
    totalRows.push(`<tr><td class="label">${labels.other}</td><td class="value">${currency} ${money(quote.otherFees)}</td></tr>`);
  }
  totalRows.push(`<tr class="grand"><td class="label">${labels.total}</td><td class="value">${currency} ${money(quote.total)}</td></tr>`);

  const html = `<!doctype html>
<html lang="${escapeHtml(language)}" dir="${direction}">
<head>
<meta charset="utf-8" />
<title>${escapeHtml(quote.quoteNo)} · ${escapeHtml(customer?.company ?? '')}</title>
<style>${documentStyles('#0b5cad')}</style>
</head>
<body class="${rtl ? 'rtl' : ''}">
<div class="doc">
  <header class="doc-header">
    <div>
      <div class="seller-name">${escapeHtml(company.name)}</div>
      ${company.nameZh ? `<div class="seller-meta">${escapeHtml(company.nameZh)}</div>` : ''}
      <div class="seller-meta">${escapeHtml([company.address, `${company.city}, ${company.country}`].filter(Boolean).join('\n'))}</div>
      <div class="seller-meta"><bdi>${escapeHtml([company.email, company.phone, company.website].filter(Boolean).join(' · '))}</bdi></div>
    </div>
    <div class="doc-title">
      <div class="label">${labels.quotation}</div>
      <div class="no">${escapeHtml(quote.quoteNo)}</div>
      <div class="date">${labels.date}: ${date(quote.createdAt)}</div>
      <div class="date">${labels.validUntil}: ${date(quote.validUntil)}</div>
    </div>
  </header>

  <section class="parties">
    <div class="party">
      <h3>${labels.buyer}</h3>
      <div class="name">${escapeHtml(customer?.company ?? '—')}</div>
      ${customer?.contactName ? `<div class="line">${labels.attn}: ${escapeHtml(customer.contactName)}</div>` : ''}
      ${customer?.email ? `<div class="line"><bdi>${escapeHtml(customer.email)}</bdi></div>` : ''}
      ${customer?.phone ? `<div class="line"><bdi>${escapeHtml(customer.phone)}</bdi></div>` : ''}
      ${customer?.country ? `<div class="line">${escapeHtml(customer.country)}</div>` : ''}
    </div>
    <div class="party">
      <h3>${labels.seller}</h3>
      <div class="name">${escapeHtml(sales.senderName)}</div>
      <div class="line">${escapeHtml(sales.senderRole)}</div>
      <div class="line"><bdi>${escapeHtml(sales.senderEmail)}</bdi></div>
      <div class="line">${escapeHtml(company.name)}</div>
    </div>
  </section>

  <table class="items">
    <thead>
      <tr>
        <th style="width:7%">${labels.item}</th>
        <th>${labels.description}</th>
        <th style="width:11%" class="num">${labels.qty}</th>
        <th style="width:9%">${labels.unit}</th>
        <th style="width:15%" class="num">${labels.unitPrice}</th>
        <th style="width:16%" class="num">${labels.amount}</th>
      </tr>
    </thead>
    <tbody>${rows || `<tr><td colspan="6">—</td></tr>`}</tbody>
  </table>

  <div class="totals">
    <table>${totalRows.join('')}</table>
  </div>

  <section class="terms">
    <h3>${labels.terms}</h3>
    <dl>
      <dt>${labels.currency}</dt><dd>${escapeHtml(currency)}</dd>
      <dt>${labels.incoterm}</dt><dd><bdi>${escapeHtml(quote.incoterm)} ${escapeHtml(quote.incotermPlace)}</bdi></dd>
      <dt>${labels.payment}</dt><dd><bdi>${escapeHtml(quote.paymentTerms ?? company.paymentTerms)}</bdi></dd>
      <dt>${labels.leadTime}</dt><dd>${quote.leadTimeDays ?? company.defaultLeadTimeDays} ${labels.days}</dd>
      ${quote.moq ? `<dt>${labels.moq}</dt><dd>${quote.moq}</dd>` : ''}
    </dl>
  </section>

  ${quote.notes ? `<div class="notes">${labels.notes}: ${escapeHtml(quote.notes)}</div>` : ''}

  <section class="signature">
    <div class="block">
      <div>${labels.signature}</div>
      <div style="margin-top:16px">${escapeHtml(sales.senderName)} · ${escapeHtml(sales.senderRole)}</div>
    </div>
    <div class="stamp">${labels.stamp}</div>
  </section>

  <footer class="doc-footer">
    ${escapeHtml(company.name)} · ${escapeHtml(company.email)} · ${escapeHtml(company.website)}<br/>
    ${labels.generated} · ${escapeHtml(quote.quoteNo)}
  </footer>
</div>
</body>
</html>`;

  return { html, baseName: quote.quoteNo, language };
}

/** Renders (and caches) the quote PDF. Returns the path, or null when unavailable. */
export async function generateQuotePdf(quoteId: string): Promise<string | null> {
  const built = buildQuoteHtml(quoteId);
  if (!built) return null;
  const rendered: RenderedDocument = await renderDocument({
    html: built.html,
    baseName: built.baseName,
    subdir: 'quotes',
  });
  return rendered.pdfPath ?? rendered.htmlPath;
}

export async function getQuotePdfPath(quoteId: string): Promise<string | null> {
  const quote = getQuote(quoteId, false);
  if (!quote?.pdfPath) return null;
  return existsSync(quote.pdfPath) ? quote.pdfPath : null;
}
